- hosts: database
  remote_user: root
  pre_tasks:
    - name: Read vars from file
      include_vars: vars.yml

  roles:
    - common
    - database

- hosts: web
  remote_user: root
  pre_tasks:
    - name: Read vars from file
    include_vars: vars.yml

  roles:
    - common
    - web
