---

- name: debug print variable users
  debug: 
    msg: "username: {{ username }}"
  when: debug_enabled_default | bool

- name: Lock users | Lock password & ssh key authentication
  user:
    name: "{{ username }}"
    expires: 0 #lock account if not locked
#  command: chage -E 0 {{ username }} #Alternative lock password & ssh key authentication
#  register: user_results
  loop_control:
    label: "username: {{ username }}"
