---
- debug: msg="System {{ ansible_os_family }}"


- name: Utilisation de YUM
  import_tasks: yum.yml
  when: ansible_os_family == "RedHat"
        
- name: Utilisation de APT
  import_tasks: apt.yml
  when: ansible_os_family == "Debian"
...
